version: '2.3'
services:
  mstracer:
    build: ./
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    working_dir: /mstracer
    ports:
      - 25:25
    volumes:
      - ./:/mstracer
      - ./data:/data
    command: tail -f /dev/null
